I"ú9<p>https://github.com/dominikh/go-tools
<!-- more -->
oo often we discover subtle bugs only after deploying to production. Even in a language like Go it‚Äôs possible to write ineffectual code and not catch bugs until it‚Äôs too late.</p>

<p>Staticcheck is a static analysis tool for Go code. It has various checks, such as a check for unused variables, a check for deferring the Lock method on a mutex right after locking (the user probably meant to defer Unlock instead), a check for unreachable code, and more.</p>

<p>In this post we‚Äôll show sample code for which staticcheck returns errors, and how to fix the affected code.</p>

<p>Value is never used (SA4006)
I always double check these errors as they can cause some serious bugs. Here‚Äôs one example:</p>

<p>package main</p>

<p>import (
	‚Äúerrors‚Äù
	‚Äúfmt‚Äù
	‚Äúlog‚Äù
)</p>

<p>type Result struct {
	Entries []string
}</p>

<p>func Query() (Result, error) {
	return Result{
		Entries: []string{},
	}, nil
}</p>

<p>func ResultEntries() (Result, error) {
	err := errors.New(‚Äúno entries found‚Äù)
	result, err := Query()
	if err != nil {
		return Result{}, err
	}
	if len(result.Entries) == 0 {
		return Result{}, err
	}
	return result, nil
}</p>

<p>func main() {
	result, err := ResultEntries()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf(‚Äúresult=%v, err=%v‚Äù, result, err)
}
When running staticcheck on this code, we see the following errors:</p>

<p>$ staticcheck main.go
main.go:20:2: this value of err is never used (SA4006)
main.go:20:19: New is a pure function but its return value is ignored (SA4017)
We‚Äôre going to ignore the second error as it‚Äôs a side effect of the first.</p>

<p>If we run the code, we see:</p>

<p>$ go run main.go
result={[]}, err=<nil>
Let's investigate:</nil></p>

<p>We have two functions, Query() and ResultEntries(). The Query function returns an empty set of entries for the purpose of this example. The ResultEntries() function declares an error at the top, err := errors.New(‚Äúno entries found‚Äù), and then calls Query() right below that to get the result.</p>

<p>This call to Query, however, overwrites the err variable to <nil> when the error returned is nil. So when we check the length of result.Entries and find that it's 0, we return Result{}, err but the err we're returning is not the err we declared at the top of the function, but rather the <nil> error which was returned by Query().</nil></nil></p>

<p>This example is quite harmless but one can imagine how similar code might lead to a more serious bug.</p>

<p>So how do we fix it?</p>

<p>The method you choose to fix this will depend on your preferred style. Here is one way:</p>

<p>func ResultEntries() (Result, error) {
	result, err := Query()
	if err != nil {
		return Result{}, err
	}</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>err = errors.New("no entries found")
if len(result.Entries) == 0 {
	return Result{}, err
}

return result, nil } Here we reassign the err variable before checking the length of result.Entries. This will now return the correct error:
</code></pre></div></div>

<p>$ go run main.go
2019/09/18 19:03:40 no entries found
exit status 1
and staticcheck no longer complains:</p>

<p>$ staticcheck main.go
$
Another way would be:</p>

<p>func ResultEntries() (Result, error) {
	result, err := Query()
	if err != nil {
		return Result{}, err
	}</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>if len(result.Entries) == 0 {
	return Result{}, errors.New("no entries found")
}

return result, nil } Calling regexp.MatchString in a loop has poor performance (SA6000) If staticcheck finds this issue in your code, you can fix it for better performance. Here's an example (note: this is not an extensive regular expression for matching emails):
</code></pre></div></div>

<p>package main</p>

<p>import (
	‚Äúfmt‚Äù
	‚Äúlog‚Äù
	‚Äúregexp‚Äù
)</p>

<p>func ValidateEmails(addrs []string) (bool, error) {
	for _, email := range addrs {
		matched, err := regexp.MatchString(‚Äú^[a-zA-Z0-9.]+@[a-zA-Z0-9]+\.[a-zA-Z0-9]*$‚Äù, email)
		if err != nil {
			return false, err
		}</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>	if !matched {
		return false, nil
	}
}

return true, nil }
</code></pre></div></div>

<p>func main() {
	emails := []string{‚Äútestuser@gmail.com‚Äù, ‚Äúanotheruser@yahoo.com‚Äù, ‚Äúonemoreuser@hotmail.com‚Äù}</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>matched, err := ValidateEmails(emails)
if err != nil {
	log.Fatal(err)
}

fmt.Println(matched) } In this example we pass a slice of email addresses to a validation function that matches them with a regular expression. Staticcheck finds the following issue:
</code></pre></div></div>

<p>$ staticcheck main.go
main.go:11:37: calling regexp.MatchString in a loop has poor performance, consider using regexp.Compile (SA6000)
Let‚Äôs fix it and then look at some benchmarks.</p>

<p>To fix the issue we‚Äôll compile the regular expression at the beginning of the function instead of recreating it in the loop every iteration:</p>

<p>func ValidateEmails(addrs []string) (bool, error) {
	re := regexp.MustCompile(<code class="language-plaintext highlighter-rouge">^[a-zA-Z0-9.]+@[a-zA-Z0-9]+\.[a-zA-Z0-9]*$</code>)
	for _, email := range addrs {
		matched := re.MatchString(email)</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>	if !matched {
		return false, nil
	}
}

return true, nil } The method regexp.MustCompile creates a reusable regular expression struct and panics if it can't be compiled. You may have noticed that the string changed slightly, but we'll ignore that for the purposes of this post it's not relevant to the overall fix. If we run staticcheck on this new code, we see no errors:
</code></pre></div></div>

<p>$ staticcheck main.go
$
The code runs and returns true:</p>

<p>$ go run main.go
true
Now let‚Äôs write a benchmark to compare these two methods. We‚Äôll call the original method ValidateEmailsRegexpLoop, and keep the current implementation called ValidateEmails:</p>

<p>package main</p>

<p>import ‚Äútesting‚Äù</p>

<p>func BenchmarkValidateEmailsRegexpLoop(b *testing.B) {
	emails := []string{‚Äútestuser@gmail.com‚Äù, ‚Äúanotheruser@yahoo.com‚Äù, ‚Äúonemoreuser@hotmail.com‚Äù}
	for i := 0; i &lt; b.N; i++ {
		_, err := ValidateEmailsRegexpLoop(emails)
		if err != nil {
			b.Fatal(err)
		}
	}
}</p>

<p>func BenchmarkValidateEmails(b *testing.B) {
	emails := []string{‚Äútestuser@gmail.com‚Äù, ‚Äúanotheruser@yahoo.com‚Äù, ‚Äúonemoreuser@hotmail.com‚Äù}
	for i := 0; i &lt; b.N; i++ {
		_, err := ValidateEmails(emails)
		if err != nil {
			b.Fatal(err)
		}
	}
}
Let‚Äôs run this benchmark:</p>

<p>$ go test -bench=.
goos: darwin
goarch: amd64
BenchmarkValidateEmailsRegexpLoop-4         100000         21150 ns/op
BenchmarkValidateEmails-4                   200000          8108 ns/op
PASS
ok      _/Users/gopher  4.045s
There is a significant performance improvement by declaring the regular expression once outside of the loop. Thanks staticcheck!</p>

<p>Running Staticcheck on popular open source codebases
As the co-creator of Go Report Card, I‚Äôm passionate about open source code quality. Let‚Äôs take a look at staticcheck results for some popular open source repositories.</p>

<p>aws/aws-sdk-go
github.com/aws/aws-sdk-go is the official AWS SDK for Go. To install it, run:</p>

<p>$ go get github.com/aws/aws-sdk-go
and then:</p>

<p>$ cd $GOPATH/src/github.com/aws/aws-sdk-go
Staticcheck takes a long time to run on the entire codebase, so let‚Äôs run it on a single directory and its sub-directories:</p>

<p>$ aws-sdk-go git:(master) staticcheck ./aws/‚Ä¶
There are many results. The one in particular we‚Äôll take a look at is:</p>

<p>aws/request/request_retry_test.go:133:2: unreachable case clause: github.com/aws/aws-sdk-go/aws/request.temporary will always match before *net/url.Error (SA4020)
Here is the function:</p>

<p>func debugerr(t *testing.T, err error) {
	t.Logf(‚ÄúError, %v‚Äù, err)</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>switch err := err.(type) {
case temporary:
	t.Logf("%s is a temporary error: %t", err, err.Temporary())
	return
case *url.Error:
	t.Logf("err: %s, nested err: %#v", err, err.Err)
	if operr, ok := err.Err.(*net.OpError); ok {
		t.Logf("operr: %#v", operr)
	}
	debugerr(t, err.Err)
	return
default:
	return
} } We need to take a look at the temporary type definition as well as url.Error to see what's going on. The temporary type is located in aws/request/retryer.go:
</code></pre></div></div>

<p>type temporary interface {
    Temporary() bool
}
and in the stdlib net/url package we‚Äôll find a concrete type Error that implements a Temporary() method (along with some others). In other words, url.Error implements the temporary interface.</p>

<p>To break it down, let‚Äôs imagine that we do pass a url.Error to the debugerr function. We go into the type switch and ask, ‚Äúis this value‚Äôs type temporary?‚Äù The answer is ‚Äúyes‚Äù because url.Error implements the Temporary() method, the only method in the temporary interface. Thus we enter that case and return ‚Äì and we never get to case *url.Error.</p>

<p>This can be fixed by swapping the case statements:</p>

<p>func debugerr(t *testing.T, err error) {
	t.Logf(‚ÄúError, %v‚Äù, err)</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>switch err := err.(type) {
case *url.Error:
	t.Logf("err: %s, nested err: %#v", err, err.Err)
	if operr, ok := err.Err.(*net.OpError); ok {
		t.Logf("operr: %#v", operr)
	}
	debugerr(t, err.Err)
	return
case temporary:
	t.Logf("%s is a temporary error: %t", err, err.Temporary())
	return
default:
	return
} } Now, if we pass a url.Error to this function, it will match in the first case statement.
</code></pre></div></div>

<p>Staticcheck also finds other issues that could be fixed in small PRs. Here are a few that stood out to me:</p>

<p>service/s3/host_style_bucket.go:70:2: var accelElem is unused (U1000)
service/glacier/treehash.go:58:5: should omit nil check; len() for nil slices is defined as zero (S1009)
service/s3/s3manager/upload.go:366:2: field bufferUploadPool is unused (U1000)
Kubernetes
Staticcheck found many issues in Kubernetes. Let‚Äôs take a look at some of them:</p>

<p>First, we‚Äôll get the source:</p>

<p>go get k8s.io/kubernetes
Kubernetes is quite a large codebase, so this time we‚Äôll just focus on one package, pkg/volume:</p>

<p>staticcheck ./pkg/volume/‚Ä¶
There are many results, but we‚Äôll focus on one of them for now:</p>

<p>pkg/volume/azure_file/azure_file.go:122:31: this value of err is never used (SA4006)
If we take a look at that code, we see the following function:</p>

<p>func (plugin *azureFilePlugin) newMounterInternal(spec *volume.Spec, pod *v1.Pod, util azureUtil, mounter mount.Interface) (volume.Mounter, error) {
	share, readOnly, err := getVolumeSource(spec)
	if err != nil {
		return nil, err
	}
	secretName, secretNamespace, err := getSecretNameAndNamespace(spec, pod.Namespace)
	return &amp;azureFileMounter{
		azureFile: &amp;azureFile{
			volName:         spec.Name(),
			mounter:         mounter,
			pod:             pod,
			plugin:          plugin,
			MetricsProvider: volume.NewMetricsStatFS(getPath(pod.UID, spec.Name(), plugin.host)),
		},
		util:            util,
		secretNamespace: secretNamespace,
		secretName:      secretName,
		shareName:       share,
		readOnly:        readOnly,
		mountOptions:    volutil.MountOptionFromSpec(spec),
	}, nil
}
We can see that the error returned by the getSecretNameAndNamespace function is ignored. We should add an error check:</p>

<p>func (plugin *azureFilePlugin) newMounterInternal(spec *volume.Spec, pod *v1.Pod, util azureUtil, mounter mount.Interface) (volume.Mounter, error) {
  share, readOnly, err := getVolumeSource(spec)
  if err != nil {
    return nil, err
  }
  secretName, secretNamespace, err := getSecretNameAndNamespace(spec, pod.Namespace)
  if err != nil {
    return nil, err
  }
  return &amp;azureFileMounter{
    azureFile: &amp;azureFile{
      volName:         spec.Name(),
      mounter:         mounter,
      pod:             pod,
      plugin:          plugin,
      MetricsProvider: volume.NewMetricsStatFS(getPath(pod.UID, spec.Name(), plugin.host)),
    },
    util:            util,
    secretNamespace: secretNamespace,
    secretName:      secretName,
    shareName:       share,
    readOnly:        readOnly,
    mountOptions:    volutil.MountOptionFromSpec(spec),
  }, nil
}
The Go source tree
That‚Äôs right, staticcheck even found some bugs in the Go source itself!</p>

<p>To be fair, it didn‚Äôt find anything egregious, but I didn‚Äôt run it on every package so it‚Äôs possible there are some more bugs hiding elsewhere.</p>

<p>We‚Äôll take a look at another unused error variable in a file called database/sql/sql_test.go. The test is TestTxEndBadConn:</p>

<p>dbQuery := func(endTx func(tx *Tx) error) func() error {
	return func() error {
		tx, err := db.Begin()
		if err != nil {
			return err
		}
		rows, err := tx.Query(‚ÄúSELECT|t1|age,name|‚Äù)
		if err == nil {
			err = rows.Close()
		} else {
			return err
		}
		return endTx(tx)
	}
}
Staticcheck tells us the following:</p>

<p>database/sql/sql_test.go:2888:5: this value of err is never used (SA4006)
This refers to the line err = rows.Close(). We can fix it by checking the error:</p>

<p>dbQuery := func(endTx func(tx *Tx) error) func() error {
	return func() error {
		tx, err := db.Begin()
		if err != nil {
			return err
		}
		rows, err := tx.Query(‚ÄúSELECT|t1|age,name|‚Äù)
		if err == nil {
			err = rows.Close()
			if err != nil {
				return err
			}
		} else {
			return err
		}
		return endTx(tx)
	}
}
Or perhaps this is more idiomatic:</p>

<p>dbQuery := func(endTx func(tx *Tx) error) func() error {
	return func() error {
		tx, err := db.Begin()
		if err != nil {
			return err
		}
		rows, err := tx.Query(‚ÄúSELECT|t1|age,name|‚Äù)
		if err != nil {
			return err
		}</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>	err = rows.Close()
	if err != nil {
		return err
	}

	return endTx(tx)
} } There are other functions in the same test file that call rows.Close() without checking the error, so maybe that is fine too.
</code></pre></div></div>

<p>If you‚Äôve been wanting to make a contribution to the Go source code, this could be your chance.</p>
:ET